version: "3.9"
services:
  bustawin:
    build:
      context: .
      target: pro-start
    restart: unless-stopped
    volumes:
      - ./build:/app/build
      - ./posts:/app/posts
      - ./jutils:/app/jutils
      - ./src.server:/app/src.server

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .tunnel.env
