services:
  bustawin:
    build:
      context: .
      target: start
    restart: unless-stopped
    volumes:
      - ./posts:/app/posts
    ports: # Only used to access from the host to test
      - 3210:3210
  
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .tunnel.env
