services:
  bustawin:
    build:
      context: .
      target: start
    restart: unless-stopped
    volumes:
      - ./posts:/app/posts
    ports: # Only used to access from the host to test
      - 3210:3210
    security_opt:
      - no-new-privileges=true  # Security: https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-4-prevent-in-container-privilege-escalation

  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .tunnel.env
